### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/diagnostics#12]
- [x] Set proper icon for settings section https://github.com/owncloud/diagnostics/issues/14

QA 
- [x] create release branch: https://github.com/owncloud/diagnostics/pull/30
- [x] bump version to 0.1.1 (initial)
- [x] create testplan and test cases Link: https://github.com/owncloud/diagnostics/issues/11 
  Waiting for https://github.com/owncloud/QA/pull/475
- [x] test and document in testplan. @SergioBertolinSG Final release "Go" Results here: https://github.com/owncloud/diagnostics/issues/11

Marketing
- [x] review summary, description @pmaier1 https://github.com/owncloud/diagnostics/pull/15
- [x] add screenshot @hurradieweltgehtunter https://github.com/owncloud/diagnostics/raw/master/img/demo1.jpg?raw=true

Build
- [x] Makefile for building app package @mrow4a 
- [x] Add changelog https://github.com/owncloud/diagnostics/issues/22
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] sign and build tarball
- [ ] upload to marketplace
- [ ] rename QA milestone to version number

**Comment by mrow4a** [comment]
@DeepDiver1975 do you have an example of Makefile for building app package? Maybe this will be useful for someone googling that and getting to this issue :>

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/firewall/blob/master/Makefile

**Comment by hurradieweltgehtunter** [comment]
please add to the checklist a notification for me if an app gets released.
ty

**Comment by mrow4a** [comment]
https://github.com/owncloud/diagnostics/pull/13 @DeepDiver1975 signing and makefile

**Comment by pmaier1** [comment]
Added PR for info.xml. Please review!

**Comment by pmaier1** [comment]
@hurradieweltgehtunter Please check screenshot and open PR

**Comment by mrow4a** [comment]
Any update here?

**Comment by individual-it** [comment]
I think @SergioBertolinSG is testing this app currently

**Comment by pmaier1** [comment]
Ready to be released

**Comment by DeepDiver1975** [comment]
https://marketplace.owncloud.com/apps/diagnostics
